<a href="https://colab.research.google.com/github/Jyotishmoy12/NeuralNetworks/blob/main/Neuralnetworks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#3 neurons 4 outputs
inputs=[1, 2, 3, 2.5]
weights1=[0.2, 0.8,-0.5, 1.0]
weights2=[0.5, -0.91, 0.26, -0.5]
weights3=[-0.26, -0.27, 0.17, 0.87]
bias1=2
bias2=3
bias3=0.5

output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
        inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
        inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
print(output )

[4.8, 1.21, 2.385]


In [8]:
inputs=[1, 2, 3, 2.5]
weights=[[0.2, 0.8,-0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases=[2, 3, 0.5]

layer_outputs=[] #output of current layer
for neuron_weights,neuron_bias in zip(weights, biases):
  neuron_output=0 #output of the given neuron
  for n_input,weight in zip(inputs, neuron_weights):
    neuron_output+=n_input*weight
  neuron_output+=neuron_bias
  layer_outputs.append(neuron_output)

print(layer_outputs)

[4.8, 1.21, 2.385]


In [9]:
import numpy as np
inputs=[1, 2, 3, 2.5]
weights=[0.2, 0.8, -0.5, 1.0]
bias=2
output=np.dot(inputs, weights)+bias
print(output)


4.8


In [10]:
#3 neurons 4 outputs
import numpy as np
inputs=[1, 2, 3, 2.5]
weights=[[0.2, 0.8,-0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases=[2, 3, 0.5]
output=np.dot(weights, inputs)+biases  #why weights are before than inputs?
#we want things to be indexed by weights not by inputs
print(output)

[4.8   1.21  2.385]


In [16]:
import numpy as np

inputs=[[1, 2, 3, 2.5],
        [2.0, 5.0, -1.0, 2.0],
        [-1.5, 2.7, 3.3, -0.8]]

weights=[[0.2, 0.8,-0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases=[2, 3, 0.5]
output=np.dot(inputs,np.array(weights).T)+biases

print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [18]:
import numpy as np

inputs=[[1, 2, 3, 2.5],
        [2.0, 5.0, -1.0, 2.0],
        [-1.5, 2.7, 3.3, -0.8]]

weights=[[0.2, 0.8,-0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases=[2, 3, 0.5]

weights2=[[0.1 , -0.14, 0.5],
         [-0.5, 0.12, -0.33],
         [-0.44, 0.73, -0.13]]

biases2=[-1, 2, -0.5]

layer1_output=np.dot(inputs,np.array(weights).T)+biases
layer2_output=np.dot(layer1_output,np.array(weights2).T)+biases2

print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [ ]:
import numpy as np

X=[[1, 2, 3, 2.5],
  [2.0, 5.0, -1.0, 2.0],
  [-1.5, 2.7, 3.3, -0.8]]


