<a href="https://colab.research.google.com/github/Jyotishmoy12/NeuralNetworks/blob/main/Neuralnetworksbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#3 neurons 4 outputs
inputs=[1, 2, 3, 2.5]
weights1=[0.2, 0.8,-0.5, 1.0]
weights2=[0.5, -0.91, 0.26, -0.5]
weights3=[-0.26, -0.27, 0.17, 0.87]
bias1=2
bias2=3
bias3=0.5

output=[inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
        inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
        inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]
print(output )

[4.8, 1.21, 2.385]


In [ ]:
inputs=[1, 2, 3, 2.5]
weights=[[0.2, 0.8,-0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases=[2, 3, 0.5]

layer_outputs=[] #output of current layer
for neuron_weights,neuron_bias in zip(weights, biases):
  neuron_output=0 #output of the given neuron
  for n_input,weight in zip(inputs, neuron_weights):
    neuron_output+=n_input*weight
  neuron_output+=neuron_bias
  layer_outputs.append(neuron_output)

print(layer_outputs)

[4.8, 1.21, 2.385]


In [ ]:
import numpy as np
inputs=[1, 2, 3, 2.5]
weights=[0.2, 0.8, -0.5, 1.0]
bias=2
output=np.dot(inputs, weights)+bias
print(output)


4.8


In [ ]:
#3 neurons 4 outputs
import numpy as np
inputs=[1, 2, 3, 2.5]
weights=[[0.2, 0.8,-0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases=[2, 3, 0.5]
output=np.dot(weights, inputs)+biases  #why weights are before than inputs?
#we want things to be indexed by weights not by inputs
print(output)

[4.8   1.21  2.385]


In [ ]:
import numpy as np

inputs=[[1, 2, 3, 2.5],
        [2.0, 5.0, -1.0, 2.0],
        [-1.5, 2.7, 3.3, -0.8]]

weights=[[0.2, 0.8,-0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases=[2, 3, 0.5]
output=np.dot(inputs,np.array(weights).T)+biases

print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [ ]:
import numpy as np

inputs=[[1, 2, 3, 2.5],
        [2.0, 5.0, -1.0, 2.0],
        [-1.5, 2.7, 3.3, -0.8]]

weights=[[0.2, 0.8,-0.5, 1.0],
         [0.5, -0.91, 0.26, -0.5],
         [-0.26, -0.27, 0.17, 0.87]]

biases=[2, 3, 0.5]

weights2=[[0.1 , -0.14, 0.5],
         [-0.5, 0.12, -0.33],
         [-0.44, 0.73, -0.13]]

biases2=[-1, 2, -0.5]

layer1_output=np.dot(inputs,np.array(weights).T)+biases
layer2_output=np.dot(layer1_output,np.array(weights2).T)+biases2

print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [ ]:
import numpy as np

np.random.seed(0)
X=[[1, 2, 3, 2.5],
  [2.0, 5.0, -1.0, 2.0],
  [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights=0.10*np.random.randn(n_inputs, n_neurons)
    self.biases=np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output=np.dot(inputs, self.weights)+self.biases

layer1=Layer_Dense(4, 5)
layer2=Layer_Dense(5, 2)

layer1.forward(X)
# print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)





[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [ ]:
#rectified linear activation function
import numpy as np

np.random.seed(0)
X=[[1, 2, 3, 2.5],
  [2.0, 5.0, -1.0, 2.0],
  [-1.5, 2.7, 3.3, -0.8]]

inputs=[0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
outputs=[]
for i in inputs:
  if i>0:
    outputs.append(i)
  elif i<=0:
    outputs.append(0)

print(outputs)


[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [ ]:
pip install nnfs

In [ ]:
import numpy as np

np.random.seed(0)
X=[[1, 2, 3, 2.5],
  [2.0, 5.0, -1.0, 2.0],
  [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights=0.10*np.random.randn(n_inputs, n_neurons)
    self.biases=np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output=np.dot(inputs, self.weights)+self.biases


class Activation_ReLU:
  def forward(self, inputs):
    self.output=np.maximum(0,inputs)

layer1=Layer_Dense(4, 5)
layer2=Layer_Dense(5, 2)

layer1.forward(X)
# print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

In [ ]:
def spiral_data(points, classes):
    X = np.zeros((points*classes, 2))
    y = np.zeros(points*classes, dtype='uint8')
    for class_number in range(classes):
        ix = range(points*class_number, points*(class_number+1))
        r = np.linspace(0.0, 1, points)  # radius
        t = np.linspace(class_number*4, (class_number+1)*4, points) + np.random.randn(points)*0.2
        X[ix] = np.c_[r*np.sin(t*2.5), r*np.cos(t*2.5)]
        y[ix] = class_number
    return X, y

In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

X, y = spiral_data(100, 3)


class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases


class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()

layer1.forward(X)

# print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 4.65504505e-04
  4.56846210e-05]
 [0.00000000e+00 5.93469958e-05 0.00000000e+00 2.03573116e-04
  6.10024377e-04]
 ...
 [1.13291524e-01 0.00000000e+00 0.00000000e+00 8.11079666e-02
  0.00000000e+00]
 [1.34588361e-01 0.00000000e+00 3.09493970e-02 5.66337556e-02
  0.00000000e+00]
 [1.07817926e-01 0.00000000e+00 0.00000000e+00 8.72561932e-02
  0.00000000e+00]]


In [ ]:
#softmax activation function to resolve the negative issue for example
#if something is -900 or -20 then it's feed though the neural network we
#would never know which is -900 or -20 so to resolve this issue we need softmax activation
#function
import math

layer_outputs=[4.8, 1.21, 2.385]
E=math.e
exp_values=[]
for output in layer_outputs:
  exp_values.append(E**output)

print(exp_values)

norm_base=sum(exp_values)
norm_values=[]
for value in exp_values:
  norm_values.append(value/norm_base)

print(norm_values)
print(sum(norm_values))


[121.51041751873483, 3.353484652549023, 10.859062664920513]
[0.8952826639572619, 0.024708306782099374, 0.0800090292606387]
0.9999999999999999


In [ ]:
import numpy as np


layer_outputs=[4.8, 1.21, 2.385]
exp_values=np.exp(layer_outputs)
norm_values=exp_values/np.sum(exp_values)
print(norm_values)
print(sum(norm_values))

[0.89528266 0.02470831 0.08000903]
0.9999999999999999


In [ ]:
import numpy as np

layer_outputs=[[4.8, 1.21, 2.385],
               [8.9, 1.81, 0.2],
               [1.41, 1.051, 0.026]]

exp_values=np.exp(layer_outputs)
#axis 1 sum row wise that's what we need
#print(np.sum(layer_outputs, axis=1, keepdims=True))

norm_values=exp_values/np.sum(exp_values, axis=1, keepdims=True)

print(norm_values)


[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99001016e-01 8.32564815e-04 1.66419394e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]


In [ ]:
import numpy as np
from nnfs.datasets import spiral_data

nnfs.init()

#defining the inputs, outputs, neurons and calculating the output
class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights=0.10*np.random.randn(n_inputs, n_neurons)
    self.biases=np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output=np.dot(inputs, self.weights)+self.biases


class Activation_ReLU:
  def forward(self, inputs):
    self.output=np.maximum(0,inputs)


class Activation_Softmax:
  def forward(self,inputs):
    exp_values=np.exp(inputs-np.max(inputs, axis=1, keepdims=True))
    probabilities=exp_values/np.sum(exp_values, axis=1, keepdims=True)
    self.output=probabilities

X,y=spiral_data(samples=100, classes=3)

dense1=Layer_Dense(2,3)
activation1=Activation_ReLU()
dense2=Layer_Dense(3,3)
activation2=Activation_Softmax()

actiavtion2=Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])




[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


In [ ]:
 #categorical cross function
import math
softmax_output=[0.7, 0.1, 0.2]
#target_class=0
target_output=[1, 0, 0]

loss=-(math.log(softmax_output[0])*target_output[0]+
       math.log(softmax_output[1])*target_output[1]+
       math.log(softmax_output[2])*target_output[2])
print(loss)


0.35667494393873245


In [ ]:
import numpy as np
from nnfs.datasets import spiral_data

nnfs.init()

#defining the inputs, outputs, neurons and calculating the output
class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights=0.10*np.random.randn(n_inputs, n_neurons)
    self.biases=np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output=np.dot(inputs, self.weights)+self.biases


class Activation_ReLU:
  def forward(self, inputs):
    self.output=np.maximum(0,inputs)


class Activation_Softmax:
  def forward(self,inputs):
    exp_values=np.exp(inputs-np.max(inputs, axis=1, keepdims=True))
    probabilities=exp_values/np.sum(exp_values, axis=1, keepdims=True)
    self.output=probabilities

class Loss:
  def calculate(self, output, y):
    sample_losses=self.forward(output, y)
    data_loss=np.mean(sample_losses)
    return data_loss

class Loss_CategoricalCrossentropy(Loss):
  def forward(self, y_pred, y_true):
    sample=len(y_pred)
    y_pred_cliped=np.clip(y_pred, 1e-7, 1-1e-7)



X,y=spiral_data(samples=100, classes=3)

dense1=Layer_Dense(2,3)
activation1=Activation_ReLU()
dense2=Layer_Dense(3,3)
activation2=Activation_Softmax()

actiavtion2=Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

